//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplashPageWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedCode
    {
        public int id { get; set; }
        public string code { get; set; }
        public string email { get; set; }
        public System.DateTime datetime { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public string fullname { get; set; }
        public System.DateTime expiredTime { get; set; }
    }
}
